## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      before_install:
        - julia -e 'import Pkg; Pkg.add("Documenter")'
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
        # - julia docs/make.jl
        # - julia -e 'using Pkg; Pkg.test("HeartRateVariability", coverage=true)'
      after_success:
        # - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
