# This file is machine-generated - editing it directly is not advised

manifest_format = "2.0"

[[deps.AutoGrad]]
git-tree-sha1 = "af6676c95cc79e658ce181aa04789fab89066d97"
repo-rev = "master"
repo-url = "https://github.com/denizyuret/AutoGrad.jl.git"
uuid = "6710c13c-97f1-543f-91c5-74e8f7d95b35"
version = "1.2.5"


