# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # make the docs:
      #
      - name: make the docs
        run: |
          echo make documentation
          pwd
          julia -e 'import Pkg; Pkg.add("Documenter")'
          julia docs/make.jl

      # run tests:
      #
      # - name: run the tests and report results
      #   run: |
      #     echo testing
      #     julia -e 'import Pkg; Pkg.add("Test")'
      #     julia -e 'using Pkg; Pkg.test("NNHelferlein", coverage=true)'
      #     julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
